
export const SPECIAL_NAMES: Record<string, string> = {
    "Beatport": "beatport.png",
    "Beatport New Releases": "beatport.png",
    "Transitions": "Transitions.png",
    "Bootlegs": "bootleg.png",
    "Crate Connect": "crate-connect.png",
    "Cuba Remix": "cubaremixes.png",
    "Redrums": "redrum.png",
    "Spin Back Promos": "spinback-promos.png",
    "Bangerz Army": "bangerzarmy.png",
    "Crack 4 DJs": "Crack4DJS.png",
    "Da Throwbackz": "Throwbacks.png",
    "FRP": "FRP.png",
    "HMC": "HMC.png",
    "Kuts": "KUTS.png",
    "MMP": "MMP.png",
    "Platinum Pool": "POOL_Platinum.png",
    "Traxsource New Releases": "traxsource.png",
    "Unlimited Latin": "UnlimitedLatin.png",
    "Latin Throwback": "latin throwback.png",
    "Latin Remixes": "latinremixes.png",
    "Cuban Pool": "Cuban-Pool.png",
    "Dale Mas Bajo": "Dale-Mas-Bajo.png",
    "Elite Remix": "Elite-Remix.png",
    "BPM Supreme": "bpmsupreme.png",
    "DJ City": "djcity.png",
    "8th Wonder": "8thwonder.png",
    "Beat Junkies": "beatjunkies.png",
    "BPM Latino": "bpmlatino.png",
    "Club Killers": "clubkillers.png",
    "Crooklyn Clan": "crooklynclan.png",
    "Digital DJ Pool": "ddp.png",
    "DMS": "dms.png",
    "Direct Music Service": "dms.png",
    "Heavy Hits": "heavyhits.png",
    "Hyperz": "hyperz.png",
    "My Mp3 Pool": "mymp3pool.png",
    "Remix Planet": "remixplanet.png",
    "The Mash Up": "themashup.png",
    "DMP": "dmp.png",
    "Promo Only": "promo-only.png",
    "Spinback Promos": "spinback-promos.png",
    "Acapellas": "acapellas.png",
    "All In One": "allinone.png",
    "America Remix": "americaremix.png",
    "BarBangerz": "barbangerz.png",
    "Beatfreakz": "beatfreakz.png",
    "California Remix": "californiaremix.png",
    "Da Zone": "dazone.png",
    "Doing The Damage": "doing-the-damage-dtm.png",
    "Europa Remix": "europaremix.png",
    "Extended Latino": "Extended-Latino.png",
    "Instrumentals": "instrumentals.png",
    "Intensa": "Intensa.png",
    "Jestei Pool": "Jestei-Pool.png",
    "Just Play": "justplay.png",
    "Latin Box": "Latin-Box.png",
    "Mixinit": "mixinit.png",
    "PLR": "PLR.png",
    "RunderGround": "RunderGround.png",
    "Xtendamix": "xtendamix.png",
    "ZipDJ": "zipdj.png"
};

export const MONTH_MAP: { [key: string]: number } = {
    'JAN': 1, 'FEB': 2, 'MAR': 3, 'APR': 4, 'MAY': 5, 'JUN': 6,
    'JUL': 7, 'AUG': 8, 'SEP': 9, 'OCT': 10, 'NOV': 11, 'DEC': 12
};
